import os
from factorialBasecase import *

"""
get the names of the java files that are to be analyzed
path is the pathname to the java file directory
"""
def getFileNames(path):
	fileList = []
	subDirList = []
	for dirpath, dirnames, filenames in os.walk(path):
		fileList.append(filenames)
		#print dirpath
		subDirList.append(dirpath)
	flatFileList = [item for sublist in fileList for item in sublist]
	flatFileList[:] = [x for x in flatFileList if x != '.DS_Store']
	return flatFileList

""" 
use the event id from each file name to generate an SQL query
that gets the compilation time and userid associated with
each event
takes in a flat file list of file names, as generated by the 
getFileNames function
"""
def generateQueries(flatFileList):
	query = "SELECT id, source_time, user_id FROM master_events WHERE" 
	for fileName in flatFileList:
		ID = getID(fileName)
		query += " id = '" + ID + "' OR"
	query = query[:-3]
	query += ";"
	return query

"""
extract event id from each file name
"""
def getID(fileName):
	passedUnderscore = False
	idString = ""
	for x in fileName:
		if x == "_" and passedUnderscore:
			break
		elif x == "_" and not passedUnderscore:
			passedUnderscore = True
		elif passedUnderscore:
			idString += x
	return idString

